### ISSUE TITLE
Visualization with raspa2.0

### ISSUE THREAD

**Issue by assoua** [iRASPA/RASPA2#8]
Hello everyone!

I have been performing hydrogen adsorption simulations on MOFs for some time. but since then I have faced the visualization problem. the RASPA tutorial says that we can visualize the density and even the molecules with vtk but I still can't. I simulate RASPA2.0 on my PC with a Linux environment. I need your help, please.

**Comment by HeliumMH** [comment]
I encounter similar problems too. 

I installed vtk and try to compile the program in examples/visulisation, but errors pop up.

So far, I think the problem is with the out-of-date functions from vtk in main.cxx, such as "vtkRayVolumeCastComposite.h" and others. These functions have been deprecanted for quite a while. And the "main.cxx" used to generate excutables in the example/visulisation was only updated 2 years ago according to this repo.

The solution is either manually update the main.cxx by yourself (if you know c++ and vtk well) or wait for someone to update the   
example files.

**Comment by dubbelda** [comment]
The "vtkRayVolumeCastComposite.h" has been deprecated by VTK. The VTK-code has been updated to use the newer volume-rendering methods.

**Comment by assoua** [comment]
Hello,
I am a Cameroonian researcher, and my research is on hydrogen adsorbing
materials, mainly MOFs.
Since I met your software RASPA, I use it for my research, which allowed me
to have two publications in this field :
https://link.springer.com/article/10.1007/s00289-020-03350-w,
https://link.springer.com/article/10.1007/s42452-020-03627-9.
I am currently working on a project ''Evaluation of the Flexibility of
Metal-Organics Frameworks for Hydrogen Adsorption Storage at Ambient
Temperature and Pressure''.
But we get stuck in the definition of the force fields. It is true that
there is in the software an example of Dubbeldamflexible-IRMOF-1, however I
have a little difficulty understanding this.
I'm writing to you for help in this sense, as I would like to do this for
other MOFs that I could design or doped.
I would also like a collaboration if possible.
Cordially

*Gustave Assoualaye**Ph.D in energetics and environment *

*Department of Renewable Energy of  National Advanced School of Engineering
of Maroua,The University of Maroua. Cameroon*
Tel: +237 697909091/ +237 680662934
